// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (c) 2025-2026 Christoph Heinrichs and Fabian Januszewski
// This file is part of cuda-mpqs (GPU-accelerated SIQS/MPQS factorization).
// See LICENSE at the repository root for licensing terms, including the NVIDIA CUDA Toolkit exception.
//
// Stage 3 genus-correctness unit test for the branch-fixed character-bit
// evaluator mpqs::matrix::branchCharBit (src/matrix/gpu_char_cols.cuh).
//
// branchCharBit(axb_mod_q, t_s, q) = [ Legendre( ((ax+b) − t_s) / q ) == −1 ],
// the branch-sensitive genus character of characters.md §3. This test certifies
// the Stage-3 acceptance gate:
//
//   (1) REFERENCE PARITY vs the genus-correct Python reference. The fixture
//       branch_char_fixture.h is generated by gen_branch_char_fixture.py from the
//       SAME branch_bit_raw / tonelli_root / legendre_pm used in the deep-example
//       genus proof (character_fix_prototype.py, validated by
//       character_fix_genus_worked.py). Every direct triple
//       (axb_mod_q, t_s, q, bit) must reproduce exactly, including 64-bit aux
//       primes q > 1e11 (the production branch regime) and the jacobi==0 case.
//
//   (2) HOMOMORPHISM. The branch character is multiplicative, hence additive over
//       F2: branchCharBit(product field element) == bit_i XOR bit_j. Each homo
//       fixture row carries the product field element and the two factor bits.
//
//   (3) HOST == DEVICE parity. Over >= 1e4 random (axb_mod_q, t_s, q) triples for
//       several 64-bit q, the host call and a device-kernel call of branchCharBit
//       must be bit-identical.
//
// Compiled as CUDA (the evaluator is __host__ __device__). Links mpqs_matrix
// (branchCharBit) + mpqs_sieve (jacobi_u64 cross-check) + mpqs_common.
//
// Exit code 0 iff every assertion passes (0 mismatches in all three checks).

#include "gpu_char_cols.cuh"    // mpqs::matrix::branchCharBit, jacobi_symbol_dev_u64
#include "prime_algorithms.h"   // mpqs::sieve::jacobi_u64 (independent cross-check)
#include "uint128_helper.cuh"   // mpqs::math::sub_mod

#include "branch_char_fixture.h"  // kBranchDirect[], kBranchHomo[] (auto-generated)

#include <cstdint>
#include <cstdio>
#include <random>
#include <vector>

#include <cuda_runtime.h>

using mpqs::matrix::branchCharBit;
using mpqs::sqrtfix::kBranchDirect;
using mpqs::sqrtfix::kBranchDirectCount;
using mpqs::sqrtfix::kBranchHomo;
using mpqs::sqrtfix::kBranchHomoCount;

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond, msg) do {                                            \
    ++g_checks;                                                          \
    if (!(cond)) { ++g_failures;                                         \
        std::printf("  FAIL: %s  (%s:%d)\n", (msg), __FILE__, __LINE__); \
    }                                                                    \
} while (0)

// ---- Device-side batch evaluation of branchCharBit (for host==device parity) --
__global__ void branchCharBitKernel(const uint64_t* axb, const uint64_t* ts,
                                    const uint64_t* q, int* out, int n) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n) out[i] = branchCharBit(axb[i], ts[i], q[i]);
}

// ---- (1) Reference parity: C++ branchCharBit == Python branch bit -------------
static void test_reference_parity() {
    int before = g_failures;
    int mismatches = 0;
    for (int i = 0; i < kBranchDirectCount; ++i) {
        const auto& c = kBranchDirect[i];
        int got = branchCharBit(c.axb_mod_q, c.t_s, c.q);
        if (got != c.bit) {
            ++mismatches;
            if (mismatches <= 8) {
                std::printf("  FAIL[direct %d]: branchCharBit(%llu,%llu,%llu)=%d "
                            "expected %d\n", i,
                            (unsigned long long)c.axb_mod_q,
                            (unsigned long long)c.t_s,
                            (unsigned long long)c.q, got, c.bit);
            }
        }
    }
    CHECK(mismatches == 0, "reference parity: all direct branch bits match Python");
    std::printf("[%s] reference parity: %d/%d direct triples match genus reference\n",
                g_failures == before ? "PASS" : "FAIL",
                kBranchDirectCount - mismatches, kBranchDirectCount);
}

// ---- (2) Homomorphism: branchCharBit(product) == bit_i XOR bit_j --------------
static void test_homomorphism() {
    int before = g_failures;
    int mismatches = 0;
    for (int i = 0; i < kBranchHomoCount; ++i) {
        const auto& c = kBranchHomo[i];
        int got = branchCharBit(c.axb_prod_mod_q, c.t_s, c.q);
        int expected = c.bit_i ^ c.bit_j;
        if (got != expected) {
            ++mismatches;
            if (mismatches <= 8) {
                std::printf("  FAIL[homo %d]: branchCharBit(prod=%llu,%llu,%llu)=%d "
                            "expected bit_i^bit_j = %d^%d = %d\n", i,
                            (unsigned long long)c.axb_prod_mod_q,
                            (unsigned long long)c.t_s,
                            (unsigned long long)c.q, got,
                            c.bit_i, c.bit_j, expected);
            }
        }
    }
    CHECK(mismatches == 0,
          "homomorphism: branchCharBit(product) == XOR of factor bits");
    std::printf("[%s] homomorphism: %d/%d product field elements XOR-consistent\n",
                g_failures == before ? "PASS" : "FAIL",
                kBranchHomoCount - mismatches, kBranchHomoCount);
}

// ---- (3) Host == device parity over >= 1e4 random triples ---------------------
static void test_host_device_parity() {
    int before = g_failures;

    // Several 64-bit odd q (incl. production-scale aux primes > 1e11).
    const uint64_t qs[] = {
        101ull, 1000003ull, 4294967311ull,             // small / ~2^32
        100000000003ull, 100000000019ull,              // ~1e11 (lp1_bound scale)
        1000000000039ull, 9999999999971ull,            // ~1e12 / ~1e13
        18446744073709551557ull                        // largest 64-bit prime
    };
    const int n_q = static_cast<int>(sizeof(qs) / sizeof(qs[0]));
    const int per_q = 2000;                            // 8 * 2000 = 16000 >= 1e4

    std::mt19937_64 rng(0xBADC0FFEE0DDF00Dull);
    std::vector<uint64_t> h_axb, h_ts, h_q;
    for (int qi = 0; qi < n_q; ++qi) {
        uint64_t q = qs[qi];
        std::uniform_int_distribution<uint64_t> dist(0, q - 1);
        for (int j = 0; j < per_q; ++j) {
            h_axb.push_back(dist(rng));
            h_ts.push_back(dist(rng));
            h_q.push_back(q);
        }
        // Always include the diff==0 corner (axb == t_s -> jacobi 0 -> bit 0).
        h_axb.push_back(12345ull % q);
        h_ts.push_back(12345ull % q);
        h_q.push_back(q);
    }
    const int n = static_cast<int>(h_axb.size());

    // Host evaluation.
    std::vector<int> h_out(n);
    for (int i = 0; i < n; ++i) h_out[i] = branchCharBit(h_axb[i], h_ts[i], h_q[i]);

    // Device evaluation.
    uint64_t *d_axb = nullptr, *d_ts = nullptr, *d_q = nullptr;
    int *d_out = nullptr;
    bool cuda_ok = true;
    auto ck = [&](cudaError_t e, const char* what) {
        if (e != cudaSuccess) {
            cuda_ok = false;
            std::printf("  CUDA ERROR (%s): %s\n", what, cudaGetErrorString(e));
        }
    };
    ck(cudaMalloc(&d_axb, n * sizeof(uint64_t)), "malloc axb");
    ck(cudaMalloc(&d_ts,  n * sizeof(uint64_t)), "malloc ts");
    ck(cudaMalloc(&d_q,   n * sizeof(uint64_t)), "malloc q");
    ck(cudaMalloc(&d_out, n * sizeof(int)),      "malloc out");

    if (cuda_ok) {
        ck(cudaMemcpy(d_axb, h_axb.data(), n * sizeof(uint64_t), cudaMemcpyHostToDevice), "memcpy axb");
        ck(cudaMemcpy(d_ts,  h_ts.data(),  n * sizeof(uint64_t), cudaMemcpyHostToDevice), "memcpy ts");
        ck(cudaMemcpy(d_q,   h_q.data(),   n * sizeof(uint64_t), cudaMemcpyHostToDevice), "memcpy q");

        int block = 256, grid = (n + block - 1) / block;
        branchCharBitKernel<<<grid, block>>>(d_axb, d_ts, d_q, d_out, n);
        ck(cudaGetLastError(), "kernel launch");
        ck(cudaDeviceSynchronize(), "kernel sync");
    }

    std::vector<int> d_host(n, -1);
    if (cuda_ok) {
        ck(cudaMemcpy(d_host.data(), d_out, n * sizeof(int), cudaMemcpyDeviceToHost), "memcpy out");
    }

    cudaFree(d_axb); cudaFree(d_ts); cudaFree(d_q); cudaFree(d_out);

    CHECK(cuda_ok, "host==device: CUDA path executed without error");

    int mismatches = 0;
    if (cuda_ok) {
        for (int i = 0; i < n; ++i) {
            if (h_out[i] != d_host[i]) {
                ++mismatches;
                if (mismatches <= 8) {
                    std::printf("  FAIL[hd %d]: host=%d device=%d  axb=%llu ts=%llu q=%llu\n",
                                i, h_out[i], d_host[i],
                                (unsigned long long)h_axb[i],
                                (unsigned long long)h_ts[i],
                                (unsigned long long)h_q[i]);
                }
            }
        }
    }
    CHECK(mismatches == 0, "host==device: bit-identical over all random triples");
    std::printf("[%s] host==device parity: %d random triples, %d mismatches\n",
                (g_failures == before) ? "PASS" : "FAIL", n, mismatches);
}

int main() {
    std::printf("=== test_branch_char_bit (Stage 3 genus correctness) ===\n");
    std::printf("fixture: %d direct + %d homomorphism cases\n",
                kBranchDirectCount, kBranchHomoCount);

    test_reference_parity();
    test_homomorphism();
    test_host_device_parity();

    std::printf("---------------------------------------------------\n");
    std::printf("checks run: %d, failures: %d\n", g_checks, g_failures);
    if (g_failures == 0) { std::printf("RESULT: PASS (0 failures)\n"); return 0; }
    std::printf("RESULT: FAIL (%d failures)\n", g_failures);
    return 1;
}
