// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (c) 2024-2026 Fabian Januszewski
// This file is part of the Block Wiedemann implementation.
// See LICENSE for licensing terms, including the NVIDIA CUDA Toolkit exception.

/**
 * @file solution_reconstructor.cu
 * @brief Stage 3: Solution Reconstruction Implementation.
 * 
 * Reconstructs the kernel vector w (where B*w = 0) from the generator polynomial
 * computed in Stage 2.
 * 
 * The reconstruction formula is derived from the block Wiedemann relation:
 *    A(x) * F(x) = G(x) + O(x^L)
 * which implies that the high-order coefficients of the sequence generated by
 * projection correspond to the kernel.
 * 
 * Specifically, for a candidate column u(x) = sum u_k x^k of the generator matrix Pi,
 * the solution vector w is computed via a Horner-like evaluation:
 *    w = sum_{k=0}^{deg} B^(deg-k) * Z * u_k
 * 
 * This file implements this evaluation using the SpMM engine for B (or B^T)
 * and dense linear algebra kernels for the Z * u_k operations.
 */
#include "lingen/stage3/solution_reconstructor.h"
#include "lingen/operations/matmul_gf2.h"
#include "hpc_logger.h"
#include "lingen/io/hash.h" 

#include <algorithm>
#include <cstring>
#include <iostream>
#include <iomanip>
#include <vector>
#include <stdexcept>
#include <string>

namespace lingen {
namespace stage3 {

#define CHECK_CUDA_REC(call) do { \
    cudaError_t err = (call); \
    if (err != cudaSuccess) { \
        LOG(LOG_ERROR_CRITICAL) << "[SolutionReconstructor] CUDA Error: " \
                                << cudaGetErrorString(err) << " at " << __FILE__ << ":" << __LINE__; \
        throw std::runtime_error("CUDA error: " + std::string(cudaGetErrorString(err))); \
    } \
} while(0)

// -----------------------------------------------------------------------------
// CUDA Kernels
// -----------------------------------------------------------------------------

__global__ void k_add_mul_Z_u_general(
    uint64_t* __restrict__ dDest, 
    const uint64_t* __restrict__ dZ, 
    const uint64_t* __restrict__ d_u, 
    int nrows, 
    int n_block
) {
    int row = blockIdx.x * blockDim.x + threadIdx.x;
    if (row >= nrows) return;
    int words_per_row = (n_block + 63) / 64;
    bool dot = false;
    for (int w = 0; w < words_per_row; ++w) {
        uint64_t z_word = dZ[row * words_per_row + w];
        uint64_t u_word = d_u[w];
        dot ^= (__popcll(z_word & u_word) & 1);
    }
    if (dot) dDest[row * words_per_row] ^= 1ULL; 
}

__global__ void k_replicate_matrix(
    uint64_t* __restrict__ dst,
    const uint64_t* __restrict__ src,
    int num_blocks,
    int mat_size_words
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= mat_size_words) return;
    uint64_t val = src[idx];
    for(int b = 0; b < num_blocks; ++b) dst[b * mat_size_words + idx] = val;
}

__global__ void k_xor_accumulate(
    uint64_t* __restrict__ dst,
    const uint64_t* __restrict__ src,
    size_t total_words
) {
    size_t idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < total_words) dst[idx] ^= src[idx];
}

__global__ void k_extract_column(
    uint64_t* __restrict__ d_vec,
    const uint64_t* __restrict__ d_batch,
    int col_idx,
    int nrows,
    int n_block
) {
    int row = blockIdx.x * blockDim.x + threadIdx.x;
    if (row >= nrows) return;
    int words_per_row = (n_block + 63) / 64;
    uint64_t word = d_batch[row * words_per_row + (col_idx / 64)];
    uint64_t bit = (word >> (col_idx % 64)) & 1ULL;
    if (bit) d_vec[row * words_per_row] |= 1ULL;
    else d_vec[row * words_per_row] &= ~1ULL;
}

__global__ void k_check_column_zeros(
    int* __restrict__ d_col_status,
    const uint64_t* __restrict__ d_batch,
    int nrows,
    int n_block
) {
    int col = blockIdx.x; 
    if (col >= n_block) return;
    
    int words_per_row = (n_block + 63) / 64;
    int tid = threadIdx.x;
    int stride = blockDim.x;
    
    int local_is_zero = 1;
    for (int r = tid; r < nrows; r += stride) {
        uint64_t word = d_batch[r * words_per_row + (col / 64)];
        if ((word >> (col % 64)) & 1ULL) {
            local_is_zero = 0;
            break;
        }
    }
    
    int has_bit = !local_is_zero;
    for (int offset = 16; offset > 0; offset /= 2) 
        has_bit |= __shfl_down_sync(0xFFFFFFFF, has_bit, offset);
        
    __shared__ int shm[32]; 
    if ((tid % 32) == 0) shm[tid / 32] = has_bit;
    __syncthreads();
    
    if (tid < 32) {
        int val = (tid < (blockDim.x + 31)/32) ? shm[tid] : 0;
        for (int offset = 16; offset > 0; offset /= 2)
            val |= __shfl_down_sync(0xFFFFFFFF, val, offset);
        if (tid == 0) d_col_status[col] = (val == 0) ? 1 : 0;
    }
}

__global__ void k_backtrack_column(
    int* __restrict__ d_found_idx,
    const uint64_t* __restrict__ d_history,
    int col,
    int cursor,
    int depth,
    int nrows,
    int n_block
) {
    int tid = threadIdx.x;
    int words_per_row = (n_block + 63) / 64;
    size_t batch_size_words = (size_t)nrows * words_per_row;
    
    if (tid == 0) *d_found_idx = -1;
    __syncthreads();

    for (int back = 1; back < depth; ++back) {
        int hist_idx = (cursor - back + depth) % depth;
        const uint64_t* d_snapshot = d_history + hist_idx * batch_size_words;
        
        int has_bit = 0;
        for (int r = tid; r < nrows; r += blockDim.x) {
            uint64_t word = d_snapshot[r * words_per_row + (col / 64)];
            if ((word >> (col % 64)) & 1ULL) {
                has_bit = 1;
                break;
            }
        }
        
        for (int offset = 16; offset > 0; offset /= 2) 
            has_bit |= __shfl_down_sync(0xFFFFFFFF, has_bit, offset);
            
        __shared__ int block_has_bit;
        if (tid == 0) block_has_bit = 0;
        __syncthreads();
        
        if ((tid % 32) == 0 && has_bit) atomicOr(&block_has_bit, 1);
        __syncthreads();
        
        if (block_has_bit) {
            if (tid == 0) *d_found_idx = hist_idx;
            return;
        }
    }
}

// -----------------------------------------------------------------------------
// Helper Functions
// -----------------------------------------------------------------------------

static std::vector<uint64_t> extract_coeff_vector(
    const std::vector<uint64_t>& hPi, 
    int M, 
    int n_block, 
    int degree_k, 
    int row_idx
) {
    size_t words_per_row_M = (M + 63) / 64;
    size_t mat_stride = M * words_per_row_M;
    const uint64_t* mat_ptr = hPi.data() + degree_k * mat_stride;
    const uint64_t* row_ptr = mat_ptr + row_idx * words_per_row_M;
    std::vector<uint64_t> u_vec((n_block + 63) / 64, 0);
    int words_needed = (n_block + 63) / 64;
    for(int w=0; w<words_needed; ++w) u_vec[w] = row_ptr[w];
    return u_vec;
}

// -----------------------------------------------------------------------------
// Class Implementation
// -----------------------------------------------------------------------------

SolutionReconstructor::SolutionReconstructor(
    const lingen::BwOperator& op, const BWStage3Config& config
) : op_(op), config_(config)
{
    // Initialize convenience members from config
    nrows_ = config_.nrows;
    m_block_ = config_.m_block;
    n_block_ = config_.n_block;
    
    // Initialize tuning parameters
    history_depth_ = config_.history_depth;
    check_interval_ = config_.check_interval;
    
    // Align nrows to n_block boundary for block-based MatMul
    nrows_aligned_ = (nrows_ + n_block_ - 1) / n_block_ * n_block_;
    
    size_t words_per_row = (n_block_ + 63) / 64;
    size_t total_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);  

    d_Z_ = nullptr;
    d_W_acc_ = nullptr;
    d_W_batch_ = nullptr;
    d_Tmp_ = nullptr;
    d_u_vec_ = nullptr;
    d_U_small_ = nullptr;
    d_U_expanded_ = nullptr;
    d_MatMul_Res_ = nullptr;
    d_extracted_sol_ = nullptr;
    d_history_ = nullptr;
    d_col_status_ = nullptr;
    d_found_idx_ = nullptr;

    CHECK_CUDA_REC(cudaMalloc(&d_Z_, total_bytes));
    CHECK_CUDA_REC(cudaMalloc(&d_W_acc_, total_bytes));
    CHECK_CUDA_REC(cudaMalloc(&d_Tmp_, total_bytes));
    CHECK_CUDA_REC(cudaMalloc(&d_u_vec_, words_per_row * sizeof(uint64_t)));
    
    CHECK_CUDA_REC(cudaMalloc(&d_W_batch_, total_bytes));
    CHECK_CUDA_REC(cudaMalloc(&d_MatMul_Res_, total_bytes));
    CHECK_CUDA_REC(cudaMalloc(&d_U_expanded_, total_bytes)); 
    CHECK_CUDA_REC(cudaMalloc(&d_extracted_sol_, total_bytes));

    size_t u_small_bytes = n_block_ * ((n_block_ + 63) / 64) * sizeof(uint64_t);
    CHECK_CUDA_REC(cudaMalloc(&d_U_small_, u_small_bytes));
    
    CHECK_CUDA_REC(cudaMalloc(&d_history_, total_bytes * history_depth_));
    CHECK_CUDA_REC(cudaMalloc(&d_col_status_, n_block_ * sizeof(int)));
    CHECK_CUDA_REC(cudaMalloc(&d_found_idx_, sizeof(int)));

    CHECK_CUDA_REC(cudaMemset(d_Z_, 0, total_bytes));
    CHECK_CUDA_REC(cudaMemset(d_W_acc_, 0, total_bytes));
    CHECK_CUDA_REC(cudaMemset(d_W_batch_, 0, total_bytes));
    
    // Resize host buffer to aligned size to prevent overflow
    h_chk_buf_.resize(nrows_aligned_ * words_per_row);
}
 
#ifdef BW_ENABLE_CUDA_GRAPHS
#if CUDART_VERSION >= 10010
void SolutionReconstructor::destroy_proj_graph() {
    if (proj_graph_captured_) {
        cudaGraphExecDestroy(proj_graph_exec_);
        proj_graph_captured_ = false;
        proj_graph_exec_ = nullptr;
    }
}
#endif
#endif

SolutionReconstructor::~SolutionReconstructor() {
#ifdef BW_ENABLE_CUDA_GRAPHS
#if CUDART_VERSION >= 10010
    destroy_proj_graph();
#endif
#endif
    cudaFree(d_Z_);
    cudaFree(d_W_acc_);
    cudaFree(d_W_batch_);
    cudaFree(d_Tmp_);
    cudaFree(d_u_vec_);
    cudaFree(d_U_small_);
    cudaFree(d_U_expanded_);
    cudaFree(d_MatMul_Res_);
    cudaFree(d_extracted_sol_);
    cudaFree(d_history_);
    cudaFree(d_col_status_);
    cudaFree(d_found_idx_);
}

void SolutionReconstructor::Init(const std::vector<uint64_t>& hY,
                                 const std::vector<uint64_t>& hPi,
                                 cudaStream_t stream) 
{
    LOG(LOG_STATS) << "[SolutionReconstructor] Initializing Search State...";
    ptr_hPi_ = &hPi;
    M_ = m_block_ + n_block_;

    size_t words_per_row = (n_block_ + 63) / 64;
    size_t valid_bytes = nrows_ * words_per_row * sizeof(uint64_t);
    size_t alloc_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);
    
    // Zero out Z completely (including padding area)
    CHECK_CUDA_REC(cudaMemsetAsync(d_Z_, 0, alloc_bytes, stream));
    // Copy only the valid rows from host
    CHECK_CUDA_REC(cudaMemcpyAsync(d_Z_, hY.data(), valid_bytes, cudaMemcpyHostToDevice, stream));

    size_t mat_stride = M_ * ((M_ + 63) / 64);
    if (mat_stride == 0) return; 
    int degree_len = (int)(hPi.size() / mat_stride);
    
    candidate_queue_.clear();
    batch_queue_.clear();
    solution_buffer_.clear();
    basis_struct_.clear();
    queue_cursor_ = 0;

    LOG_INCREMENT_STAGE(10);
    LOG(LOG_DEBUG_2) << "[SolutionReconstructor] [Init] Extracting degrees...";
    for (int r = 0; r < M_; ++r) {
        int deg = -1;
        for (int k = degree_len - 1; k >= 0; --k) {
            auto u = extract_coeff_vector(hPi, M_, n_block_, k, r);
            bool nz = false;
            for(auto x : u) if(x) nz = true;
            if (nz) { deg = k; break; }
        }
        if (deg != -1) candidate_queue_.push_back({deg, r});
    }

    std::sort(candidate_queue_.begin(), candidate_queue_.end());

    if (config_.batch_mode) {
        LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Building batches...";
        BatchCandidate current_batch;
        current_batch.max_degree = -1;
        for (const auto& cand : candidate_queue_) {
            current_batch.candidates.push_back(cand);
            current_batch.max_degree = std::max(current_batch.max_degree, cand.degree);
            if (current_batch.candidates.size() >= (uint64_t)n_block_) {
                batch_queue_.push_back(current_batch);
                current_batch = BatchCandidate();
                current_batch.max_degree = -1;
            }
        }
        if (!current_batch.candidates.empty()) batch_queue_.push_back(current_batch);
        LOG(LOG_STATS) << "[SolutionReconstructor] Batch Mode: Created " << batch_queue_.size() << " batches.";
    } else {
        LOG(LOG_STATS) << "[SolutionReconstructor] Legacy Mode: " << candidate_queue_.size() << " candidates queued.";
    }
}

bool SolutionReconstructor::FindNext(std::vector<uint64_t>& out_solution, cudaStream_t stream) {
    if (config_.batch_mode) return FindNextBatch(out_solution, stream);
    else return FindNextLegacy(out_solution, stream);
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

void SolutionReconstructor::construct_batch_matrix(
    std::vector<uint64_t>& out_U, 
    int n_block, 
    const std::vector<uint64_t>& hPi, 
    int M, 
    int k, 
    const std::vector<Candidate>& batch
) {
    size_t words_per_row = (n_block + 63) / 64;
    std::fill(out_U.begin(), out_U.end(), 0);
    for (size_t col = 0; col < batch.size(); ++col) {
        const auto& cand = batch[col];
        if (k > cand.degree) continue; 
        auto u_vec = extract_coeff_vector(hPi, M, n_block, k, cand.col_idx);
        for (int row = 0; row < n_block; ++row) {
            uint64_t bit = (u_vec[row / 64] >> (row % 64)) & 1ULL;
            if (bit) out_U[row * words_per_row + (col / 64)] |= (1ULL << (col % 64));
        }
    }
}

// -----------------------------------------------------------------------------
// Batch Execution Logic
// -----------------------------------------------------------------------------
bool SolutionReconstructor::FindNextBatch(std::vector<uint64_t>& out_solution, cudaStream_t stream) {
    if (!ptr_hPi_) return false;

    // 1. Drain Buffer
    if (!solution_buffer_.empty()) {
        out_solution = solution_buffer_.front();
        solution_buffer_.pop_front();
        return true;
    }

    size_t words_per_row = (n_block_ + 63) / 64;
    size_t total_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);

    // 2. Process Next Batch
    while (!batch_queue_.empty()) {
        BatchCandidate batch = batch_queue_.front();
        batch_queue_.pop_front();

        LOG(LOG_DEBUG_1) << "[SolutionReconstructor] Processing Batch of size " << batch.candidates.size() 
                         << ", MaxDeg=" << batch.max_degree;

        // Reset
        CHECK_CUDA_REC(cudaMemsetAsync(d_W_batch_, 0, total_bytes, stream));
    
        std::vector<uint64_t> h_U(n_block_ * words_per_row);

        // Determine if graph capture is worthwhile for this batch
#ifdef BW_ENABLE_CUDA_GRAPHS
#if CUDART_VERSION >= 10010
        bool use_graph_this_batch = config_.use_cuda_graph
                                 && (batch.max_degree >= config_.graph_min_iterations)
                                 && !config_.oracle_verification;
#endif
#endif

        // --- Parallel Horner Loop ---
        for (int k = 0; k <= batch.max_degree; ++k) {
	    if (!(k % 100) && k > 0)
	      LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Horner Loop Degree = " << k << " (" << 100.0*(float)k/(float)batch.max_degree << "%)";

            // A. Shift
            if (k > 0) {
                CHECK_CUDA_REC(cudaMemsetAsync(d_Tmp_, 0, total_bytes, stream));
                op_.mul(d_Tmp_, d_W_batch_, stream);
                CHECK_CUDA_REC(cudaMemcpyAsync(d_W_batch_, d_Tmp_, total_bytes, cudaMemcpyDeviceToDevice, stream));
            }

            // B. Project
            construct_batch_matrix(h_U, n_block_, *ptr_hPi_, M_, k, batch.candidates);
            CHECK_CUDA_REC(cudaMemcpyAsync(d_U_small_, h_U.data(), h_U.size()*sizeof(uint64_t), cudaMemcpyHostToDevice, stream));

            int num_blocks = nrows_aligned_ / n_block_;
            int u_words = h_U.size();
            int threads = 256;
            size_t total_w = nrows_aligned_ * words_per_row;

#ifdef BW_ENABLE_CUDA_GRAPHS
#if CUDART_VERSION >= 10010
            if (use_graph_this_batch) {
                if (!proj_graph_captured_) {
                    // First iteration: capture the 3-kernel projection chain
                    cudaError_t cap_err = cudaStreamBeginCapture(stream,
                                                                  cudaStreamCaptureModeThreadLocal);
                    if (cap_err != cudaSuccess) {
                        LOG(LOG_WARNING) << "[SolutionReconstructor] Graph capture begin failed: "
                                         << cudaGetErrorString(cap_err) << ". Falling back to direct launches.";
                        use_graph_this_batch = false;
                    } else {
                        int blocks_rep = (u_words + threads - 1) / threads;
                        k_replicate_matrix<<<blocks_rep, threads, 0, stream>>>(
                            d_U_expanded_, d_U_small_, num_blocks, u_words);

                        matmul_gf2_gpu(n_block_, d_Z_, d_U_expanded_, d_MatMul_Res_, num_blocks, stream);

                        int blocks_xor = (total_w + threads - 1) / threads;
                        k_xor_accumulate<<<blocks_xor, threads, 0, stream>>>(
                            d_W_batch_, d_MatMul_Res_, total_w);

                        cudaGraph_t graph;
                        cap_err = cudaStreamEndCapture(stream, &graph);
                        if (cap_err != cudaSuccess || graph == nullptr) {
                            LOG(LOG_WARNING) << "[SolutionReconstructor] Graph capture failed: "
                                             << cudaGetErrorString(cap_err) << ". Falling back to direct launches.";
                            use_graph_this_batch = false;
                        } else {
                            cap_err = cudaGraphInstantiate(&proj_graph_exec_, graph, nullptr, nullptr, 0);
                            cudaGraphDestroy(graph);
                            if (cap_err != cudaSuccess) {
                                LOG(LOG_WARNING) << "[SolutionReconstructor] Graph instantiation failed: "
                                                 << cudaGetErrorString(cap_err) << ". Falling back to direct launches.";
                                proj_graph_exec_ = nullptr;
                                use_graph_this_batch = false;
                            } else {
                                proj_graph_captured_ = true;
                                LOG(LOG_DEBUG_2) << "[SolutionReconstructor] CUDA graph captured for projection chain ("
                                                 << "3 nodes, will replay for remaining " << batch.max_degree << " iterations)";
                            }
                        }
                    }
                }

                if (proj_graph_captured_) {
                    // Replay: H→D upload of d_U_small_ already completed above (async on stream).
                    // The graph reads from d_U_small_ which now contains the new data.
                    CHECK_CUDA_REC(cudaGraphLaunch(proj_graph_exec_, stream));
                } else {
                    // Capture failed — fall through to direct launch for this iteration
                    int blocks_rep = (u_words + threads - 1) / threads;
                    k_replicate_matrix<<<blocks_rep, threads, 0, stream>>>(
                        d_U_expanded_, d_U_small_, num_blocks, u_words);

                    matmul_gf2_gpu(n_block_, d_Z_, d_U_expanded_, d_MatMul_Res_, num_blocks, stream);

                    int blocks_xor = (total_w + threads - 1) / threads;
                    k_xor_accumulate<<<blocks_xor, threads, 0, stream>>>(
                        d_W_batch_, d_MatMul_Res_, total_w);
                }
            } else
#endif
#endif
            {
                // --- Direct Launch Path (fallback / non-graph) ---
                int blocks_rep = (u_words + threads - 1) / threads;
                k_replicate_matrix<<<blocks_rep, threads, 0, stream>>>(
                    d_U_expanded_, d_U_small_, num_blocks, u_words);

                matmul_gf2_gpu(n_block_, d_Z_, d_U_expanded_, d_MatMul_Res_, num_blocks, stream);

                int blocks_xor = (total_w + threads - 1) / threads;
                k_xor_accumulate<<<blocks_xor, threads, 0, stream>>>(
                    d_W_batch_, d_MatMul_Res_, total_w);
            }

            // C. Optional: Intermedia Verification of Horner Result (at exact degree)
	    // We do NOT strip here. We wait for the parallel RunBatchStripping phase.
            bool recording = config_.oracle_verification && oracle_data_.empty();
            bool verifying = !oracle_data_.empty();	    
	    if (recording || verifying) {
                for (int i = 0; i < batch.candidates.size(); ++i) {
                    if (batch.candidates[i].degree == k) {
		        int grid = (nrows_ + 63) / 64;
                        CHECK_CUDA_REC(cudaMemsetAsync(d_extracted_sol_, 0, total_bytes, stream));
                        k_extract_column<<<grid, 64, 0, stream>>>(d_extracted_sol_, d_W_batch_, i, nrows_, n_block_);

                        if (recording) {
			    uint64_t h = hash_device_vector(d_extracted_sol_, stream);
                            recorded_data_[batch.candidates[i].col_idx].hash_horner = h;
                        } 
                        // Only verify if we have data (avoids "missing" warning during recording)
                        if (verifying) {
                            VerifyAgainstOracle(batch.candidates[i].col_idx, d_extracted_sol_, nullptr, stream);
			}
		    }
                }
            }
        }

        // --- Parallel Valuation Stripping ---
        RunBatchStripping(batch, stream);

        if (!solution_buffer_.empty()) {
            out_solution = solution_buffer_.front();
            solution_buffer_.pop_front();
            return true;
        }
    }

    LOG(LOG_STATS) << "[SolutionReconstructor] Batch search exhausted.";
    return false;
}

void SolutionReconstructor::RunBatchStripping(const BatchCandidate& batch, cudaStream_t stream) {

    // Configure Loop Max Steps
    int max_steps;
    if (config_.stripping_step_limit > 0) {
        max_steps = config_.stripping_step_limit;
    } else {
        // Heuristic: If valuation stripping doesn't converge quickly, it's likely a spurious candidate.
        max_steps = (nrows_ / 1024 + 128 < 4096) ? nrows_ / 1024 + 128 : 4096;
    }  

    LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Batch Valuation Stripping with max_steps = " << max_steps;
    
    size_t words_per_row = (n_block_ + 63) / 64;
    // Use aligned size for safe history snapshots
    size_t total_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);
    int grid = (nrows_ + 63) / 64;
    
    // Status tracking
    std::vector<int> h_col_status(n_block_);
    // All candidates are active initially
    std::vector<bool> is_active(batch.candidates.size(), true);
    int active_count = batch.candidates.size();  

    if (active_count == 0) return;
    
    int cursor = 0;
    
    // Save initial state (step 0 of stripping)
    CHECK_CUDA_REC(cudaMemcpyAsync(d_history_ + cursor * (total_bytes/8), d_W_batch_, total_bytes, cudaMemcpyDeviceToDevice, stream));
    
    for (int step = 1; step <= max_steps; ++step) {
        
        // Advance cursor
        cursor = (cursor + 1) % history_depth_;
        
        // Compute Next Step: W = B * W
        CHECK_CUDA_REC(cudaMemsetAsync(d_Tmp_, 0, total_bytes, stream));
        op_.mul(d_Tmp_, d_W_batch_, stream);
        CHECK_CUDA_REC(cudaMemcpyAsync(d_W_batch_, d_Tmp_, total_bytes, cudaMemcpyDeviceToDevice, stream));

        // Save to History
        uint64_t* d_snap = d_history_ + cursor * (total_bytes/8);
        CHECK_CUDA_REC(cudaMemcpyAsync(d_snap, d_W_batch_, total_bytes, cudaMemcpyDeviceToDevice, stream));
        
        // Check Interval
        if (step % check_interval_ == 0) {
            // Check zeros
            k_check_column_zeros<<<n_block_, 256, 0, stream>>>(d_col_status_, d_W_batch_, nrows_, n_block_);
            CHECK_CUDA_REC(cudaMemcpyAsync(h_col_status.data(), d_col_status_, n_block_ * sizeof(int), cudaMemcpyDeviceToHost, stream));
            CHECK_CUDA_REC(cudaStreamSynchronize(stream));
            
            // for (int i = 0; i < batch.candidates.size(); ++i) {
            for (int i = batch.candidates.size() - 1; i >= 0; --i) {
                if (is_active[i] && h_col_status[i] == 1) {
                    // Column died since last check.
                    // Backtrack to find last non-zero.
                    // Use nrows_aligned_ for correct history stride
                    k_backtrack_column<<<1, 256, 0, stream>>>(
                        d_found_idx_, d_history_, i, cursor, history_depth_, nrows_aligned_, n_block_
                    );
                    int found_idx = -1;
                    CHECK_CUDA_REC(cudaMemcpyAsync(&found_idx, d_found_idx_, sizeof(int), cudaMemcpyDeviceToHost, stream));
                    CHECK_CUDA_REC(cudaStreamSynchronize(stream));
                    
                    if (found_idx != -1) {
                        // Extract solution from history
                        uint64_t* d_source = d_history_ + found_idx * (total_bytes/8);
                        CHECK_CUDA_REC(cudaMemsetAsync(d_extracted_sol_, 0, total_bytes, stream));
                        k_extract_column<<<grid, 64, 0, stream>>>(d_extracted_sol_, d_source, i, nrows_, n_block_);
                        
                        // Verify & Store
                        const auto& cand = batch.candidates[i];
                        
                        // Verification (Final)
                        if (config_.oracle_verification && oracle_data_.empty()) {
			    // Recording
                            uint64_t f = hash_device_vector(d_extracted_sol_, stream);
                            recorded_data_[cand.col_idx].hash_final = f;
                        }
                        if (!oracle_data_.empty()) {
                            VerifyAgainstOracle(cand.col_idx, nullptr, d_extracted_sol_, stream);
                        }

                        // Download: Use aligned buffer to prevent overflow
                        std::vector<uint64_t> hW(nrows_aligned_ * words_per_row);
                        CHECK_CUDA_REC(cudaMemcpyAsync(hW.data(), d_extracted_sol_, total_bytes, cudaMemcpyDeviceToHost, stream));
                        CHECK_CUDA_REC(cudaStreamSynchronize(stream));
                        
                        std::vector<uint64_t> w_packed((nrows_ + 63) / 64, 0);
                        int weight = 0;
                        for (int r = 0; r < nrows_; ++r) {
                            if (hW[r * words_per_row] & 1ULL) {
                                w_packed[r / 64] |= (1ULL << (r % 64));
                                weight++;
                            }
                        }
                        
                        if (weight > 0) {
                            if (insert_into_basis(basis_struct_, w_packed)) {
                                LOG(LOG_DEBUG_1) << "[SolutionReconstructor] Found Independent Solution #" 
                                              << basis_struct_.size() << " (Weight: " << weight 
                                              << ", Source: Col " << cand.col_idx << ")";
                                solution_buffer_.push_back(basis_struct_.back().vec);
                            }
                        }
                    } else {
                        LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Backtrack failed for col " << i 
                                         << ". History depth " << history_depth_ << " exceeded?";
                    }
                    
                    is_active[i] = false;
                    active_count--;
                }
            }
            if (active_count == 0) break;
        }
    }
}

// -----------------------------------------------------------------------------
// Legacy Logic (Wrapper)
// -----------------------------------------------------------------------------
bool SolutionReconstructor::FindNextLegacy(std::vector<uint64_t>& out_solution, cudaStream_t stream) {
    if (!ptr_hPi_) return false;
    while (queue_cursor_ < candidate_queue_.size()) {
        const auto& cand = candidate_queue_[queue_cursor_];
        queue_cursor_++;
        if (ProcessCandidate(cand, out_solution, stream)) return true;
    }
    return false;
}

// -----------------------------------------------------------------------------
// Common Processing Logic
// -----------------------------------------------------------------------------
bool SolutionReconstructor::ProcessCandidate(const Candidate& cand, std::vector<uint64_t>& out_solution, cudaStream_t stream) {
    size_t words_per_row = (n_block_ + 63) / 64;
    // Use aligned size even in legacy to ensure buffer safety
    size_t total_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);
    int grid = (nrows_ + 63) / 64;

    LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Processing Candidate Col=" << cand.col_idx 
                     << " Deg=" << cand.degree;

    CHECK_CUDA_REC(cudaMemsetAsync(d_W_acc_, 0, total_bytes, stream));
    for (int k = 0; k <= cand.degree; ++k) {
        if (k > 0) {
            CHECK_CUDA_REC(cudaMemsetAsync(d_Tmp_, 0, total_bytes, stream));
            op_.mul(d_Tmp_, d_W_acc_, stream);
            CHECK_CUDA_REC(cudaMemcpyAsync(d_W_acc_, d_Tmp_, total_bytes, cudaMemcpyDeviceToDevice, stream));
        }
        auto u_vec = extract_coeff_vector(*ptr_hPi_, M_, n_block_, k, cand.col_idx);
        bool u_nz = false; 
        for(auto x : u_vec) if(x) u_nz=true;
        if (u_nz) {
            CHECK_CUDA_REC(cudaMemcpy(d_u_vec_, u_vec.data(), u_vec.size()*sizeof(uint64_t), cudaMemcpyHostToDevice));
            k_add_mul_Z_u_general<<<grid, 64, 0, stream>>>(d_W_acc_, d_Z_, d_u_vec_, nrows_, n_block_);
        }
    }

    if (ProcessFoundSolution(cand, d_W_acc_, stream)) {
        out_solution = basis_struct_.back().vec;
        return true;
    }
    return false;
}

bool SolutionReconstructor::ProcessFoundSolution(const Candidate& cand, uint64_t* d_sol_vec, cudaStream_t stream) {
    bool recording = config_.oracle_verification && oracle_data_.empty();
    bool verifying = !oracle_data_.empty();
    
    if (recording) {
        uint64_t h_hash = hash_device_vector(d_sol_vec, stream);
        recorded_data_[cand.col_idx].hash_horner = h_hash;
    }
    if (verifying) {
        VerifyAgainstOracle(cand.col_idx, d_sol_vec, nullptr, stream);
    }
    if (is_zero_vector(d_sol_vec, stream)) return false;
    int limit = (config_.stripping_step_limit > 0) ? config_.stripping_step_limit : (nrows_ + 128);
    bool converged = strip_valuation(d_sol_vec, d_Tmp_, limit, stream);
    if (converged) {
        if (recording) {
            uint64_t f_hash = hash_device_vector(d_sol_vec, stream);
            recorded_data_[cand.col_idx].hash_final = f_hash;
        }
        if (verifying) {
            VerifyAgainstOracle(cand.col_idx, nullptr, d_sol_vec, stream);
        }
        
        size_t words_per_row = (n_block_ + 63) / 64;
        // Use aligned size for safe download
        std::vector<uint64_t> hW(nrows_aligned_ * words_per_row);
        size_t total_bytes = nrows_aligned_ * words_per_row * sizeof(uint64_t);
        
        CHECK_CUDA_REC(cudaMemcpyAsync(hW.data(), d_sol_vec, total_bytes, cudaMemcpyDeviceToHost, stream));
        CHECK_CUDA_REC(cudaStreamSynchronize(stream));
        std::vector<uint64_t> w_packed((nrows_ + 63) / 64, 0);
        int weight = 0;
        for (int r = 0; r < nrows_; ++r) {
            if (hW[r * words_per_row] & 1ULL) {
                w_packed[r / 64] |= (1ULL << (r % 64));
                weight++;
            }
        }
        if (weight > 0 && insert_into_basis(basis_struct_, w_packed)) {
            LOG(LOG_INFO) << "[SolutionReconstructor] Found Independent Solution #" 
                          << basis_struct_.size() << " (Weight: " << weight << ", Source: Col " << cand.col_idx << ")";
            return true; 
        }
    }
    return false;
}

// -----------------------------------------------------------------------------
// Core Implementation Helpers
// -----------------------------------------------------------------------------
bool SolutionReconstructor::insert_into_basis(std::vector<BasisVector>& basis, std::vector<uint64_t>& vec) {
    bool changed = true;
    while(changed) {
        changed = false;
        int pivot = -1;
        for(size_t i=0; i<vec.size(); ++i) {
            if (vec[i] != 0) {
                pivot = i * 64 + __builtin_ctzll(vec[i]);
                break;
            }
        }
        if (pivot == -1) return false; 
        for(const auto& b : basis) {
            if (b.pivot == pivot) {
                for(size_t k=0; k<vec.size(); ++k) vec[k] ^= b.vec[k];
                changed = true;
                break;
            }
        }
    }
    int pivot = -1;
    for(size_t i=0; i<vec.size(); ++i) {
        if (vec[i] != 0) {
            pivot = i * 64 + __builtin_ctzll(vec[i]);
            break;
        }
    }
    if (pivot != -1) {
        basis.push_back({pivot, vec});
        return true;
    }
    return false;
}

/*
void SolutionReconstructor::apply_operator(void* d_out, const void* d_in) {
    if (config_.solve_transposed) spmm_.execute_AT(d_out, d_in);
    else spmm_.execute_A(d_out, d_in);
}
*/

bool SolutionReconstructor::is_zero_vector(const uint64_t* d_ptr, cudaStream_t stream) {
    size_t total_bytes = nrows_aligned_ * ((n_block_ + 63) / 64) * sizeof(uint64_t);
    CHECK_CUDA_REC(cudaMemcpyAsync(h_chk_buf_.data(), d_ptr, total_bytes, cudaMemcpyDeviceToHost, stream));
    CHECK_CUDA_REC(cudaStreamSynchronize(stream));
    for (size_t i = 0; i < h_chk_buf_.size(); ++i) if (h_chk_buf_[i] != 0) return false;
    return true;
}

bool SolutionReconstructor::strip_valuation(uint64_t* d_w, uint64_t* d_tmp, int max_steps, cudaStream_t stream) {
    size_t total_bytes = nrows_aligned_ * ((n_block_ + 63) / 64) * sizeof(uint64_t);
    CHECK_CUDA_REC(cudaMemsetAsync(d_tmp, 0, total_bytes, stream));
    op_.mul(d_tmp, d_w, stream);
    if (is_zero_vector(d_tmp, stream)) return true;
    CHECK_CUDA_REC(cudaMemcpyAsync(d_w, d_tmp, total_bytes, cudaMemcpyDeviceToDevice, stream));
    for(int step = 0; step < max_steps; ++step) {
        CHECK_CUDA_REC(cudaMemsetAsync(d_tmp, 0, total_bytes, stream));
	op_.mul(d_tmp, d_w, stream);
        if (is_zero_vector(d_tmp, stream)) return true;
        CHECK_CUDA_REC(cudaMemcpyAsync(d_w, d_tmp, total_bytes, cudaMemcpyDeviceToDevice, stream));
    }
    return false;
}

uint64_t SolutionReconstructor::hash_device_vector(const uint64_t* d_ptr, cudaStream_t stream) {
    // Note: Hashing strictly nrows_ for Oracle compatibility, even if underlying buffer is aligned
    size_t total_bytes = nrows_ * ((n_block_ + 63) / 64) * sizeof(uint64_t);
    CHECK_CUDA_REC(cudaMemcpyAsync(h_chk_buf_.data(), d_ptr, total_bytes, cudaMemcpyDeviceToHost, stream));
    CHECK_CUDA_REC(cudaStreamSynchronize(stream));
    return fnv1a_hash_uint64(h_chk_buf_);
}

void SolutionReconstructor::VerifyAgainstOracle(int candidate_col_idx, 
                                                const uint64_t* d_w_horner, 
                                                const uint64_t* d_w_final,
                                                cudaStream_t stream)
{
    auto it = oracle_data_.find(candidate_col_idx);
    if (it == oracle_data_.end()) {
        if (batch_mode_) {
            LOG(LOG_DEBUG_3) << "[SolutionReconstructor] Oracle entry missing for " << candidate_col_idx 
                             << ". Likely over-production in batch mode. Skipping verification.";
            return;
        }
        LOG(LOG_ERROR_CRITICAL) << "[SolutionReconstructor] Oracle Verification FAILED: Candidate " << candidate_col_idx << " not in oracle.";
        throw std::runtime_error("Oracle verification failed: candidate not in oracle");
    }
    const OracleEntry& ref = it->second;
    if (d_w_horner) {
        uint64_t h = hash_device_vector(d_w_horner, stream);
        if (h != ref.hash_horner) {
            LOG(LOG_ERROR_CRITICAL) << "[SolutionReconstructor] Oracle Mismatch (Horner) for " << candidate_col_idx
                                    << ": 0x" << std::hex << h << " != 0x" << ref.hash_horner << std::dec;
            throw std::runtime_error("Oracle hash mismatch (Horner)");
        }
    }
    if (d_w_final) {
        uint64_t f = hash_device_vector(d_w_final, stream);
        if (f != ref.hash_final) {
            LOG(LOG_ERROR_CRITICAL) << "[SolutionReconstructor] Oracle Mismatch (Final) for " << candidate_col_idx
                                    << ": 0x" << std::hex << f << " != 0x" << ref.hash_final << std::dec;
            throw std::runtime_error("Oracle hash mismatch (Final)");
        }
    }
    LOG(LOG_DEBUG_2) << "[SolutionReconstructor] Verified Candidate " << candidate_col_idx;
}

} // namespace stage3
} // namespace lingen
